baseURL = "http://example.org/"
languageCode = "en-us"
title = "Morgan's blog"
theme = 'ananke'

[params]
  body_classes = "helvetica bg-near-white"

[menu]
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  pre = "<i class='fa fa-heart'></i>"
  url = '/posts/'
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'
[[menu.main]]
  identifier = 'about'
  name = 'about'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'
    