baseURL = "https://morganwebdev.org/"
languageCode = "en-us"
title = "Morgan's blog"
theme = 'ananke'
show_reading_time = true

Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[params]
  body_classes = "helvetica bg-near-white"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/airbr" 

[[params.ananke_socials]]
name = "mastodon"
url = "https://subdued.social/@morganm"
rel = "me noopener"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/mmurrah/"
rel = "me noopener"
share = false

[[params.ananke_socials]]
name = "slack"
url = "https://www.bellingham.codes/"
rel = "me noopener"

[menu]
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  pre = "<i class='fa fa-heart'></i>"
  url = '/posts/'
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'
[[menu.main]]
  identifier = 'about'
  name = 'about'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'
    
    