baseURL = "https://morganwebdev.org/"
languageCode = "en-us"
title = "Morgan Murrah morganwebdev.org"
theme = 'ananke'
show_reading_time = true
features = ["posts", "shortcodes", "related content"]

Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number

enableRobotsTXT = true

[params]
  body_classes = "helvetica bg-near-white"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/airbr" 
 [[params.ananke_socials]] 
  name = "rss"
  url = "https://morganwebdev.org/index.xml" 

[menu]
[[menu.main]]
  identifier = 'writings'
  name = 'writings'
  pre = "<i class='fa fa-heart'></i>"
  url = '/posts/'
  weight = 1
  [menu.main.params]
    class = 'highlight-menu-item'
[[menu.main]]
  identifier = 'about'
  name = 'about me'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = 3
  [menu.main.params]
    class = 'highlight-menu-item'
[[menu.main]]
  identifier = 'web-performance'
  name = 'about web performance'
  pre = "<i class='fa fa-heart'></i>"
  url = '/web-performance/'
  weight = 4
[[menu.main]]
  identifier = 'uses'
  name = 'tools I use'
  pre = "<i class='fa fa-heart'></i>"
  url = '/uses/'
  weight = 5
[[menu.main]]
  identifier = 'BellinghamWA'
  name = 'BellinghamWA'
  pre = "<i class='fa fa-heart'></i>"
  url = '/Bellingham/'
  weight = 6

[[menu.main]]
  identifier = 'urls'
  name = 'hyperlinks'
  pre = "<i class='fa fa-heart'></i>"
  url = '/urls/'
  weight = 7