baseURL = "https://morganwebdev.org/"
languageCode = "en-us"
title = "Morgan Murrah - morganwebdev.org"
theme = 'ananke'
show_reading_time = true
features = ["posts", "shortcodes", "related content"]

Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number

enableRobotsTXT = true

[taxonomyPageList]
other = "Here are pages tagged with the name “{{ .Title }}”"

[params]
  body_classes = "helvetica bg-near-white"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/airbr" 
 [[params.ananke_socials]] 
  name = "rss"
  url = "https://morganwebdev.org/index.xml" 

[related]
  includeNewer = false
  threshold = 80
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 100
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 80

[menu]
[[menu.main]]
  identifier = 'writings'
  name = 'writings'
  pre = "<i class='fa fa-heart'></i>"
  url = '/posts/'
  weight = 1
  [menu.main.params]
    class = 'highlight-menu-item'
[[menu.main]]
  identifier = 'about'
  name = 'about'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = 3
  [menu.main.params]
    class = 'highlight-menu-item'
[[menu.main]]
  identifier = 'web-performance'
  name = 'web performance'
  pre = "<i class='fa fa-heart'></i>"
  url = '/web-performance/'
  weight = 4
[[menu.main]]
  identifier = 'urls'
  name = 'and hyperlinks'
  pre = "<i class='fa fa-heart'></i>"
  url = '/urls/'
  weight = 5